-- MySQL Script generated by MySQL Workbench
-- 02/19/17 15:39:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_pnp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_pnp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_pnp` DEFAULT CHARACTER SET utf8 ;
USE `db_pnp` ;

-- -----------------------------------------------------
-- Table `db_pnp`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pnp`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `auth_key` VARCHAR(32) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `password_reset_token` VARCHAR(255) NULL,
  `email` VARCHAR(255) NOT NULL,
  `status` SMALLINT(6) NOT NULL,
  `created_at` INT(11) NOT NULL,
  `updated_at` INT(11) NOT NULL,
  `lastname` VARCHAR(100) NOT NULL,
  `firstname` VARCHAR(100) NOT NULL,
  `middlename` VARCHAR(100) NOT NULL,
  `birthdate` DATE NOT NULL,
  `contact_number` INT(11) NOT NULL,
  `home_address` VARCHAR(150) NOT NULL,
  `postion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Contact Number_UNIQUE` (`contact_number` ASC),
  UNIQUE INDEX `Username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `password_reset_token_UNIQUE` (`password_reset_token` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pnp`.`facility`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pnp`.`facility` (
  `id` INT NOT NULL,
  `availability` CHAR(3) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `capacity` INT NOT NULL,
  `rate` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ID_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pnp`.`equipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pnp`.`equipment` (
  `id` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `availability` CHAR(3) NOT NULL,
  `quantity` VARCHAR(45) NOT NULL,
  `facility_id` INT NOT NULL,
  PRIMARY KEY (`id`, `facility_id`),
  UNIQUE INDEX `ID_UNIQUE` (`id` ASC),
  INDEX `fk_equipment_facility1_idx` (`facility_id` ASC),
  CONSTRAINT `fk_equipment_facility1`
    FOREIGN KEY (`facility_id`)
    REFERENCES `db_pnp`.`facility` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pnp`.`reservation_request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pnp`.`reservation_request` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(20) NOT NULL,
  `Date_Submitted` DATE NOT NULL,
  `Status` CHAR(11) NOT NULL,
  `Date_Received` DATE NOT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  INDEX `fk_reservation_request_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_reservation_request_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_pnp`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pnp`.`reservation_date`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pnp`.`reservation_date` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `actual_date_reseved` DATETIME NOT NULL,
  `actual_time_reserved` DATETIME NOT NULL,
  `reservation_request_ID` INT NOT NULL,
  PRIMARY KEY (`id`, `reservation_request_ID`),
  UNIQUE INDEX `ID_UNIQUE` (`id` ASC),
  INDEX `fk_reservation_date_reservation_request1_idx` (`reservation_request_ID` ASC),
  CONSTRAINT `fk_reservation_date_reservation_request1`
    FOREIGN KEY (`reservation_request_ID`)
    REFERENCES `db_pnp`.`reservation_request` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pnp`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pnp`.`department` (
  `id` INT NOT NULL,
  `type` VARCHAR(20) NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pnp`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pnp`.`admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `auth_key` VARCHAR(45) NOT NULL,
  `password_hash` VARCHAR(45) NOT NULL,
  `password_reset_token` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `created_at` VARCHAR(45) NOT NULL,
  `updated_at` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(20) NOT NULL,
  `firstname` VARCHAR(30) NOT NULL,
  `middlename` VARCHAR(20) NULL,
  `contact_number` INT NOT NULL,
  `rank` VARCHAR(50) NOT NULL,
  `position` VARCHAR(50) NOT NULL,
  `birthdate` DATE NULL,
  `department_id` INT NOT NULL,
  PRIMARY KEY (`id`, `department_id`),
  UNIQUE INDEX `ID_UNIQUE` (`id` ASC),
  UNIQUE INDEX `Contact Number_UNIQUE` (`contact_number` ASC),
  UNIQUE INDEX `Username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `password_reset_token_UNIQUE` (`password_reset_token` ASC),
  INDEX `fk_admin_department1_idx` (`department_id` ASC),
  CONSTRAINT `fk_admin_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `db_pnp`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pnp`.`approval_request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pnp`.`approval_request` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(20) NOT NULL,
  `status` CHAR(11) NOT NULL,
  `date_receive` DATE NOT NULL,
  `date_submitted` DATE NOT NULL,
  `date_approved` DATE NOT NULL,
  `admin_id` INT NOT NULL,
  `admin_department_id` INT NOT NULL,
  `reservation_request_ID` INT NOT NULL,
  PRIMARY KEY (`id`, `admin_id`, `admin_department_id`, `reservation_request_ID`),
  INDEX `fk_approval_request_admin1_idx` (`admin_id` ASC, `admin_department_id` ASC),
  INDEX `fk_approval_request_reservation_request1_idx` (`reservation_request_ID` ASC),
  CONSTRAINT `fk_approval_request_admin1`
    FOREIGN KEY (`admin_id` , `admin_department_id`)
    REFERENCES `db_pnp`.`admin` (`id` , `department_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_approval_request_reservation_request1`
    FOREIGN KEY (`reservation_request_ID`)
    REFERENCES `db_pnp`.`reservation_request` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pnp`.`reservation_facility`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pnp`.`reservation_facility` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `reservation_request_ID` INT NOT NULL,
  `facility_id` INT NOT NULL,
  PRIMARY KEY (`id`, `reservation_request_ID`, `facility_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_reservation_facility_reservation_request1_idx` (`reservation_request_ID` ASC),
  INDEX `fk_reservation_facility_facility1_idx` (`facility_id` ASC),
  CONSTRAINT `fk_reservation_facility_reservation_request1`
    FOREIGN KEY (`reservation_request_ID`)
    REFERENCES `db_pnp`.`reservation_request` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_facility_facility1`
    FOREIGN KEY (`facility_id`)
    REFERENCES `db_pnp`.`facility` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
